version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project123
      - POSTGRES_DB=campaign_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: campaign_redis

  app:
    container_name: campaign_demo
    build: 
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./app/:/usr/src/app/

  # celery 
  celery:
    container_name: campaign_celery
    restart: always
    build:
      context: .
    # command: ['sh', '-c', 'cd /app/demo && celery -A campaign worker -l info']
    command: celery -A demo worker -l DEBUG
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data: