version: "3.9"
   
services:
  redis:
    container_name: redis
    image: redis:6.2.7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: postgres:alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  

  backend:
    build: 
      context: .
      dockerfile: dockerfiles/prod/django/Dockerfile
    container_name: backend
    command: sh -c "gunicorn --bind 0.0.0.0:8000 demo.wsgi:application"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
  
  certbot:
    build: 
      context: ./dockerfiles/prod/certbot/
    command: echo "Skipping..."
    container_name: certbot
    env_file:
      - .env.prod
    volumes: 
      - certbot_www_volume:/vol/www/
      - certbot_certs_volume:/etc/letsencrypt/
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    build:
      context: ./dockerfiles/prod/nginx/
    restart: always
    env_file:
      - .env.prod
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - certbot_www_volume:/vol/www/
      - proxy_dhparams:/vol/proxy
      - certbot_certs_volume:/etc/letsencrypt/

    depends_on:
      - backend

  celery:
    container_name: campaign_celery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Prod
    command: celery -A demo worker -l DEBUG
    volumes:
      - .:/code
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_www_volume:
  certbot_certs_volume:
  proxy_dhparams: