version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: campaign_redis
    ports:
      - "6379:6379"

  app:
    container_name: campaign_demo
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    # volumes:
    #   - ./app/:/usr/src/app/
  # celery 
  celery:
    container_name: campaign_celery
    restart: always
    build:
      context: .
    command: celery -A demo worker -l DEBUG
    # ports:
    #   - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data:
