version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: campaign_redis
    ports:
      - "6379:6379"
  # configuring nginx
  nginx:
    container_name: nginx_campaign
    build: ./nginx/
    ports:
      - 1337:80
    depends_on:
      - app

  app:
    container_name: campaign_demo
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env.prod
    command: python usr.src.app.wsgi --bind 0.0.0.0:8000
    depends_on:
      - db
    # volumes:
    #   - ./app/:/usr/src/app/
  # celery 
  celery:
    container_name: campaign_celery
    restart: always
    build:
      context: .
    command: celery -A demo worker -l DEBUG
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data:
