name: CI Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Pull the Docker Campaign Images
        run: sudo docker pull magicpitch/campaign_demo:lastest
      - name: Pull the Docker Celery Demo Images
        run: sudo docker pull magicpitch/celery_demo:lastest
      - name: Delete old docker campaign images
        run: sudo docker rm -f campaign_demo:lastest || true
      - name: Delete old docker Celery images
        run: sudo docker rm -f celery_demo:lastest || true
      - name: Run the images
        run: docker run -d 8000:8000 --name campaign_demo magicpitch/campaign_demo

