name: CD Pipeline

on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed

jobs:


  build:
    runs-on: self-hosted

    container:
      image: docker:20.10.8
      options: --privileged  # Required for Docker-in-Docker

    services:
      redis:
        image: redis

    steps:
    # - name: Deploy to Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SHH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Delete old Docker campaign_celery container
        run: |
          docker stop campaign_celery || true
          docker rm -f campaign_celery || true

      - name: Pull the Docker Campaign Celery Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest

      # - name: Run the Docker Campaign Celery Container
      #   run: docker run -d -p 5555:5555 --name campaign_celery ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest

      - name: Delete old Docker campaign_demo container
        run: |
          docker stop campaign_demo || true
          docker rm -f campaign_demo || true

      - name: Pull the Docker Campaign Demo Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest

      - name: Run the Docker Campaign Demo Container
        run: docker run -d -p 8000:8000 --name  campaign_demo ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest