name: CD Pipeline

on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed

jobs:


  build:
    runs-on: self-hosted

    container:
      image: docker:20.10.8
      options: --privileged  # Required for Docker-in-Docker

    services:
      redis:
        image: redis

    steps:
    # - name: Deploy to Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SHH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Compose
        run: |
          apk add --no-cache docker-compose
          docker --version
          docker-compose --version

      - name: Delete old docker campaign images
        run: |
          docker stop campaign_celery || true
          docker rm campaign_celery || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest || true

      - name: Delete old docker Celery images
        run: |
          docker stop campaign_demo || true
          docker rm campaign_demo || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest
          cd demo && docker compose up -d

      - name: Pull the Docker Campaign Celery Images
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest

      - name: Pull the Docker Celery Demo Images
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest

      - name: Run the images
        run: docker compose up -d
