name: Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login into Docker
        env:
          DOCKER_URL: ${{ secrets.DOCKER_URL }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Create an env file
        run: |
          echo "${{ secrets.magicpith_env }}" > demo/.env
        shell: bash
      - name: Build the Docker images using Docker Compose
        run: |
          # Navigate to the docker-compose.yml file
          cd demo
          # Build the Docker images using Docker Compose
          docker-compose build
          # Tag the images with your Docker Hub repository name and version
          docker tag demo_app ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest
          docker tag demo_celery ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest
          docker tag demo_db ${{ secrets.DOCKER_USERNAME }}/postgres_db:lastest
          docker tag demo_redis ${{ secrets.DOCKER_USERNAME }}/campaign_redis:lastest
          # Push the images to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/campaign_demo:lastest
          docker push ${{ secrets.DOCKER_USERNAME }}/campaign_celery:lastest
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres_db:lastest
          docker push ${{ secrets.DOCKER_USERNAME }}/campaign_redis:lastest
        shell: bash
