name: Continuous Integration

on:
  push:
    branches: ["main"]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login into Docker
        env:
          DOCKER_URL: ${{ secrets.DOCKER_URL }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Create an env file
        run: |
          echo "${{ secrets.magicpith_env }}" > demo/.env
        shell: bash
      - name: List contents of demo directory
        run: ls -l demo
      - name: Build the Docker image
        run: cd demo && docker-compose up -d
      - name: Push to docker registry
        run: |
          docker push magicpitch.azureci.io/campaign_demo:lastest
          docker push magicpitch.azureci.io/campaign_celery:lastest
          docker push magicpitch.azureci.io/postgres_db:lastest
          docker push magicpitch.azureci.io/campaign_redis:lastest